### ISSUE TITLE
🛤 Reference Types

### ISSUE THREAD

**Issue by binji** [WebAssembly/proposals#10]
**This is a tracking issue for a post-MVP feature**
It will be updated as the issue progresses.

**Topic** Reference Types
**Champion** Andreas Rossberg (@rossberg)
**Status** In progress
**[Phase](https://github.com/WebAssembly/meetings/blob/master/process/phases.md)** Implementation Phase
**Linked issues**
**Linked repositories** https://github.com/WebAssembly/reference-types

**Comment by Ms2ger** [comment]
https://github.com/WebAssembly/spec/commit/7fa2f20a6df4cf1c114582c8cb60f5bfcdbf1be1
