### ISSUE TITLE
How can I access the input parameters of the if structure?

### ISSUE THREAD

**Issue by Becavalier** [WebAssembly/proposals#111]
As I am looking into the Multi-value proposal, and just wondering to know how I can access the input parameters of an "if" structure?

```
(func $xxxx (param i64 i64) (result i64)
;; ....
	(if (param i64) (result i64)
		;; how can I access the input param of the outer if structure here?
	)
)
```

**Comment by RossTate** [comment]
It's on the stack at the start of the body of the `if`.

**Comment by conrad-watt** [comment]
Unfortunately our current definition of `if` does consume the conditional value without making it available in the body. If you need the exact value, you'll need to either

- use `local.set/tee` to save the value into a local prior to entering the `if` and then retrieve it with `local.get`, or
- duplicate the value some other way and pass it as an explicit stack parameter to the body.

**Comment by Becavalier** [comment]
@conrad-watt  Got it, thanks!
