### ISSUE TITLE
Questions regarding function and their locals.

### ISSUE THREAD

**Issue by Becavalier** [WebAssembly/proposals#112]
1.  Will the functions consume stack value when it's been called if it has parameters?
2. What are the default value of the function locals if we call a `local.get` before calling `local.set`?

**Comment by tlively** [comment]
1. Yes, because the call instruction has type `[t1*] -> [t2*]`, which means it consumes the types `[t1*]` from the stack: https://webassembly.github.io/spec/core/valid/instructions.html#xref-syntax-instructions-syntax-instr-control-mathsf-call-x.

2. The default values are zeroes: https://webassembly.github.io/spec/core/exec/instructions.html#exec-invoke (see steps 4, 8, and 9).

**Comment by Becavalier** [comment]
Thanks! @tlively 
I was reading the execution process of the Wasm abstract machine, and I've found that a Label would be created when calling a function, so, what should we actually do with this Lable? Should we put it into the stack as well? Here on the spec, it only says "Enter the instruction sequence instr∗ with label 𝐿."

![image](https://user-images.githubusercontent.com/8282020/121146156-4090f200-c872-11eb-9b97-a9d27470f859.png)

**Comment by dulanov** [comment]
@Becavalier You can follow this logic by youself looking directly in reference impl. logic.

Every `Call` or `Call_indirect` should be replaced with internal single administrative instruction `Invoke` - https://github.com/WebAssembly/spec/blob/662232701afa7bef3c5b1e77362f2bab6173fca4/interpreter/exec/eval.ml#L197

After that `Invoke` should be replaced with another administrative instrustions with a new activation frame `Frame` - https://github.com/WebAssembly/spec/blob/662232701afa7bef3c5b1e77362f2bab6173fca4/interpreter/exec/eval.ml#L519

And in the last link you can see axactly how initiated local variables and how a new Label created and inserted around function body instructions. I hope this can help you to deeply understand how it works by fact.

**Comment by dulanov** [comment]
@Becavalier  @rossberg [`Return` opcode](https://webassembly.github.io/spec/core/exec/instructions.html#exec-return) can be used to jump from functon from every levels, it can be not only `br 0`, but every `br l`, oder?

**Comment by Becavalier** [comment]
Thanks! Really helpful.
