### ISSUE TITLE
Are Typed Function References dead?

### ISSUE THREAD

**Issue by TonyGuil** [WebAssembly/proposals#120]
I see that the latest wat2wasm (version 1.0.24 for Windows) has an option --enable-function-references to enable Typed Function References. I tried it out on the test suite in proposals\function-references, extracting modules from .wast files by hand.

But it doesn't work -- (ref t$), let, br_if_null etc are not recognised. Is this going to be fixed? Or am I just doing something wrong?

**Comment by rossberg** [comment]
The proposal certainly is not dead, but it is not finalised yet. I'd suggest asking on the wabt repo regarding the status of their wat2wasm tool. In the meantime, the reference interpreter in the function-refs repo is up to date with the proposal and can convert wat to wasm as well.

**Comment by dbezhetskov** [comment]
Hi, there is active PR to support part of this proposal: https://github.com/WebAssembly/wabt/pull/1695

**Comment by tlively** [comment]
Closing this issue because the question has been answered. Further discussion of this topic should take place on the typed function references repo: https://github.com/WebAssembly/function-references.
