### ISSUE TITLE
Universal Assembly - UASM

### ISSUE THREAD

**Issue by sirinath** [WebAssembly/proposals#132]
Since Wasm is finding use cases outside the browser perhaps the name can be rethought to reflect this. Also this means all the non browser use cases also considered early in designs and in proposals.

**Comment by tlively** [comment]
We already consider non-Web use cases in the design of new WebAssembly proposals and many of the active members of the WebAssembly Community Group represent non-Web interests. It's true that the name doesn't really communicate that, but it's also far too late to change the name.
