### ISSUE TITLE
🛤 WebAssembly specification

### ISSUE THREAD

**Issue by binji** [WebAssembly/proposals#15]
**This is a tracking issue for post-MVP work**
It will be updated as the issue progresses.

**Topic** WebAssembly specification
**Champion** Andreas Rossberg (@rossberg-chromium)
**Status** In progress
**[Phase](https://github.com/WebAssembly/meetings/blob/master/process/phases.md)** Proposed spec text available
**Linked issues** *none*
**Linked repositories** [github.com/WebAssembly/spec](https://github.com/WebAssembly/spec)

# Details

Formalize the WebAssembly specification including:

* Reference interpreter
* Test suite
* English and formalized description of WebAssembly including:

  - Structure of values, types, instructions, and modules
  - Validation
  - Execution
  - Binary Format
  - Text format
  - JavaScript APIs and Web embedding

**Comment by sunfishcode** [comment]
Closing as discussed in https://github.com/WebAssembly/design/issues/1534. As of https://github.com/WebAssembly/meetings/pull/561, the CG no longer uses tracking issues to track proposals. See the [proposals repo README.md](https://github.com/WebAssembly/proposals) to track the status of proposals.
