### ISSUE TITLE
Small corrections to the Roadmap page

### ISSUE THREAD

**Issue by omasanori** [WebAssembly/proposals#167]
I am sorry if this is not the right repository to report, but:

* Extended constant expressions was shipped and enabled by default in Firefox ~~90 ([Bug 1706124](https://bugzilla.mozilla.org/show_bug.cgi?id=1706124))~~ 112 ([Bug 1814421](https://bugzilla.mozilla.org/show_bug.cgi?id=1814421))
* GC is available in Firefox Nightly, requiring the `javascript.options.wasm_gc` flag to enable

**Comment by jryans** [comment]
I believe that would be tracked in the https://github.com/WebAssembly/website repo...

It looks like there's already a PR to update one of those (https://github.com/WebAssembly/website/pull/336), but it seems like someone might need to be nudged to review it...

**Comment by dschuff** [comment]
Looks like I missed it, sorry about that. Thanks for the nudge! I've landed the aforementioned PR.
