### ISSUE TITLE
🛤 Bulk memory operations

### ISSUE THREAD

**Issue by binji** [WebAssembly/proposals#18]
**This is a tracking issue for a post-MVP feature**
It will be updated as the issue progresses.

**Topic** Bulk memory operations
**Champion** Ben Smith @binji
**Status** in progress
**[Phase](https://github.com/WebAssembly/meetings/blob/master/process/phases.md)** Feature proposal
**Linked issues** https://github.com/WebAssembly/design/issues/236 https://github.com/WebAssembly/design/issues/977 https://github.com/WebAssembly/design/issues/1057
**Linked repositories** [bulk-memory-operations](https://github.com/WebAssembly/bulk-memory-operations)

# Details

Copying and clearing large memory regions is very common, and making these
operations fast is architecture dependent. Although this can be done in the MVP
via `i32.load` and `i32.store`, this requires more bytes of code and forces VMs
to recognize the loops as well. The following operators can be added to improve
performance:

* `move_memory`: Copy data from a source memory region to destination region;
   these regions may overlap: the copy is performed as if the source region was 
   first copied to a temporary buffer, then the temporary buffer is copied to
   the destination region
* `set_memory`: Set all bytes in a memory region to a given byte

We expect that WebAssembly producers will use these operations when the region
size is known to be large, and will use loads/stores otherwise.

**Comment by Ms2ger** [comment]
https://github.com/WebAssembly/spec/commit/7fa2f20a6df4cf1c114582c8cb60f5bfcdbf1be1
