### ISSUE TITLE
optional floating point support?

### ISSUE THREAD

**Issue by trcrsired** [WebAssembly/proposals#180]
Can we provide a mode to make floating point support optional? The compiler should just use soft float.

This is important for translating wasm to vanilla lua for example where you do not have proper float point support.

**Comment by dschuff** [comment]
Hi @trcrsired,
I think the [design repo](https://github.com/WebAssembly/design/issues) is the right place to file this kind of issue. It will get more visibility there (this repo is really just for documentation purposes).

**Comment by sunfishcode** [comment]
If anyone is interested in discussing this, please file a new issue in the [design repo](https://github.com/WebAssembly/design/issues).
