### ISSUE TITLE
🛤 Multi-value

### ISSUE THREAD

**Issue by binji** [WebAssembly/proposals#19]
**This is a tracking issue for a post-MVP feature**
It will be updated as the issue progresses.

**Topic** Multi-value
**Champion** Andreas Rossberg @rossberg 
**Status** in progress
**[Phase](https://github.com/WebAssembly/meetings/blob/master/process/phases.md)** Implementation phase
**Linked issues** https://github.com/WebAssembly/design/issues/937, https://github.com/WebAssembly/design/issues/667, 
**Linked repositories** [github.com/WebAssembly/multi-value](https://github.com/WebAssembly/multi-value))

# Details

* Multiple return values for functions:
  - enable unboxing of tuples or structs returned by value
  - efficient compilation of multiple return values

* Multiple results for instructions:
  - enable instructions producing several results (divmod, arithmetics with carry)

* Inputs to blocks:
  - loop labels can have arguments
  - can represent phis on backward edges
  - enable future `pick` operator to cross block boundary
  - macro definability of instructons with inputs
    * `i32.select3` = `dup if ... else ... end`

**Comment by Ms2ger** [comment]
https://github.com/WebAssembly/spec/commit/484180ba3d9d7638ba1cb400b699ffede796927c
