### ISSUE TITLE
🛤 C/C++ API

### ISSUE THREAD

**Issue by chicoxyzzy** [WebAssembly/proposals#24]
**This is a tracking issue for a post-MVP feature**
It will be updated as the issue progresses.

**Topic** C/C++ API
**Champion** Andreas Rossberg @rossberg 
**Status** in progress
**[Phase](https://github.com/WebAssembly/meetings/blob/master/process/phases.md)** Feature Proposal
**Linked repositories** https://github.com/rossberg/wasm-c-api

# Details

**Comment by sunfishcode** [comment]
Closing as discussed in https://github.com/WebAssembly/design/issues/1534. As of https://github.com/WebAssembly/meetings/pull/561, the CG no longer uses tracking issues to track proposals. See the [proposals repo README.md](https://github.com/WebAssembly/proposals) to track the status of proposals.
