### ISSUE TITLE
Public access to Chromium tracking bugs 

### ISSUE THREAD

**Issue by neelance** [WebAssembly/proposals#31]
On https://www.chromestatus.com/features#webassembly some of the tracking bugs are not publicly accessible, for example https://bugs.chromium.org/p/chromium/issues/detail?id=840415. Is this intentional?

**Comment by chicoxyzzy** [comment]
Hi! This repo is for tracking proposals to WebAssembly specifications and is not relevant to Chrome Status website or Chromium tracker. I think you should ask this question [here](https://groups.google.com/a/chromium.org/forum/#!newtopic/blink-dev) or [here](https://github.com/GoogleChrome/chromium-dashboard/issues) (both links are from Chrome Status website footer).

**Comment by neelance** [comment]
Right, the footer says "File content issue", I didn't see that. Thanks. I just thought the tracking bugs are somewhat related to the proposals and I could reach the responsible people here. I've sent a message to blink-dev now.
