### ISSUE TITLE
Create a checklist to use for new proposals

### ISSUE THREAD

**Issue by binji** [WebAssembly/proposals#40]
See comment here: https://github.com/WebAssembly/proposals/issues/38#issuecomment-481446234

* Create new repository, forked from https://github.com/WebAssembly/spec
* Update [WebAssembly/proposals repo](https://github.com/WebAssembly/proposals/blob/master/README.md)
* Create tracking issue (e.g. https://github.com/WebAssembly/proposals/issues/39)
* Enable Travis CI for repo: https://travis-ci.org/account/repositories
* Enable WebHooks: https://github.com/WebAssembly/mynewproposal/settings/hooks
* Update deploy_key.enc: https://github.com/WebAssembly/reference-types/settings/keys
  * See https://gist.github.com/domenic/ec8b0fc8ab45f39403dd
  * TODO: use https://docs.travis-ci.com/user/deployment/pages/ instead?
* Add champion as owner/collaborator of repo: https://github.com/WebAssembly/mynewproposal/settings/collaboration

**Comment by chicoxyzzy** [comment]
Probably we'll also need a checklist for proposals advancement. Seehttps://github.com/WebAssembly/design/pull/1273

**Comment by binji** [comment]
Added some steps, but I'm sure I'm missing things.

**Comment by sunfishcode** [comment]
Closing this issue, as the list above is out of date; the current process for new proposals is [here](https://github.com/WebAssembly/meetings/blob/main/process/phases.md).
