### ISSUE TITLE
A way to load existing DLL/SO?

### ISSUE THREAD

**Issue by pernghh** [WebAssembly/proposals#42]
There are a lot of dll modules (500+) that exist in our corp already that most of them written in C++ ( compile from VC 6 ~ latest) and some of them have SIMD/OpenCL/DirectX ... hardware acceleration, some of them have a long history and not possible to recompile them at all, some of them are load by other dll and some may provided by other company like Intel, ... etc. But I don't found any document that describe how it possible to integrate these modules into WebAssembly. A wrapper? 

Of course I don't assume I can use them all, part of them can integrate without problem is already great for me.

Is it possible to create a platform depend wrapper then integrate these modules into WebAssembly?

If the answer is yes, please tell me where to find the reference?

Or this is the future feature, or it's not possible to happened in WebAssembly?

**Comment by dschuff** [comment]
Unfortunately this isn't possible. WebAssembly is a different architecture from what those libraries were compiled for so, just as you can't run ARM binaries on an x86 machine without slow emulation, you can't run x86 binaries on wasm. (The same is also true for the OS APIs those binaries use).

**Comment by pernghh** [comment]
Thanks, got it!!

**Comment by Hongarc** [comment]
And we can't load DLL file, can we?

**Comment by dschuff** [comment]
No, see my above response.

**Comment by lem0nify** [comment]
@dschuff We can't **load** DLL/SO but why can't we **FFI** it?

**Comment by dschuff** [comment]
It's possible in the same way it's possible in the JVM and .NET; namely whoever implements the wasm VM would need to implement an API that exposes the underlying platform. e.g. in JVM it's only possible via  an API like the JNI; a wasm VM would need something similar. (there's no such API on the web).
