### ISSUE TITLE
🛤 Import/Export of Mutable Globals

### ISSUE THREAD

**Issue by binji** [WebAssembly/proposals#5]
**This is a tracking issue for a post-MVP feature**
It will be updated as the issue progresses.

**Topic** Import/Export of Mutable Globals
**Champion** Ben Smith @binji 
**Status** in progress
**[Phase](https://github.com/WebAssembly/meetings/blob/master/process/phases.md)** standardize
**Linked issues**
**Linked repositories** [github.com/WebAssembly/mutable-global](https://github.com/WebAssembly/mutable-global)

# Details

Imported and exported globals can now be mutable. In the Web binding, exported globals are now of type `WebAssembly.Global`, rather than converted to a JavaScript `Number`.

**Comment by Ms2ger** [comment]
https://github.com/WebAssembly/spec/commit/d8f775eed3645e689580610d101106cd1404b637
