### ISSUE TITLE
🛤 JavaScript BigInt to WebAssembly i64 integration

### ISSUE THREAD

**Issue by binji** [WebAssembly/proposals#7]
**This is a tracking issue for a post-MVP feature**
It will be updated as the issue progresses.

**Topic** JavaScript BigInt to WebAssembly i64 integration
**Champion** Dan Ehrenberg @littledan  
**Status** in progress
[**Phase**](https://github.com/WebAssembly/meetings/blob/master/process/phases.md) proposed spec text available
**Linked issues** https://github.com/WebAssembly/spec/pull/707
**Linked repositories** [github.com/WebAssembly/JS-BigInt-integration](https://github.com/WebAssembly/JS-BigInt-integration)

**Details**

With this patch, BigInts have support for bidirectionally converting
to 64-bit integer WebAssembly values, which appears as
- Parameters and return values to exported WebAssembly functions
- Parameters and return values to host functions
- Imported and exported globals

BigInts can be read or written from WebAssembly memory using the
BigInt proposal's BigInt64Array or BigUint64Array; no additional
support is needed.

**Comment by lars-t-hansen** [comment]
It's implemented in Firefox and it's been baking in Nightly for some time.  What's the status of other implementations, tools, spec text?  It would be nice to ship this if we can.

**Comment by gahaas** [comment]
It's implemented in Chrome as well. Spec tests were still lacking last time I checked.

**Comment by Ms2ger** [comment]
Spec text and tests are done in the proposal repo. Not sure if we need anything on the tools side. Given the restrictions to comment to this issue, I've created https://github.com/WebAssembly/JS-BigInt-integration/issues/32 in for further discussion.

**Comment by Ms2ger** [comment]
CG approved phase 4 in the 2020-05-12 meeting.

**Comment by sunfishcode** [comment]
Closing as discussed in https://github.com/WebAssembly/design/issues/1534. As of https://github.com/WebAssembly/meetings/pull/561, the CG no longer uses tracking issues to track proposals. See the [proposals repo README.md](https://github.com/WebAssembly/proposals) to track the status of proposals.
