### ISSUE TITLE
🛤 Sign-extension operators

### ISSUE THREAD

**Issue by binji** [WebAssembly/proposals#9]
**This is a tracking issue for a post-MVP feature**
It will be updated as the issue progresses.

**Topic** Sign-extension operators
**Champion** Ben Smith @binji
**Status** in progress
[**Phase**](https://github.com/WebAssembly/meetings/blob/master/process/phases.md) standardize the feature
**Linked issues**
**Linked repositories** [github.com/WebAssembly/sign-extension-ops](https://github.com/WebAssembly/sign-extension-ops)

# Details

This proposal adds five new integer instructions for sign-extending 8-bit, 16-bit, and 32-bit values.

  * `i32.extend8_s`: extend a signed 8-bit integer to a 32-bit integer
  * `i32.extend16_s`: extend a signed 16-bit integer to a 32-bit integer
  * `i64.extend8_s`: extend a signed 8-bit integer to a 64-bit integer
  * `i64.extend16_s`: extend a signed 16-bit integer to a 64-bit integer
  * `i64.extend32_s`: extend a signed 32-bit integer to a 64-bit integer

**Comment by sunfishcode** [comment]
Closing as discussed in https://github.com/WebAssembly/design/issues/1534. As of https://github.com/WebAssembly/meetings/pull/561, the CG no longer uses tracking issues to track proposals. See the [proposals repo README.md](https://github.com/WebAssembly/proposals) to track the status of proposals.
