### ISSUE TITLE
New reinterpretation instructions?

### ISSUE THREAD

**Issue by 00ff0000red** [WebAssembly/proposals#93]
Really small request, but I'm sure that reinterpretation instructions that split/merge their values could efficiently be implemented on most platforms.

I suggest that the following be added to Wasm:

|           Operation          |        Type signature        |
| :--------------------------- | :------------------------------ |
|   i32x2.reinterpret/i64  |         (i64): (i32 i32)         |
|   f32x2.reinterpret/i64  |        (i64): (f32 f32)         |
|   i32x2.reinterpret/f64  |         (f64): (i32 i32)         |
|   f32x2.reinterpret/f64  |        (f64): (f32 f32)         |
|   i64.reinterpret/i32x2  |         (i32 i32): (i64)         |
|   i64.reinterpret/f32x2  |        (f32 f32): (i64)         |
|   f64.reinterpret/i32x2  |         (i32 i32): (f64)         |
|   f64.reinterpret/f32x2  |        (f32 f32): (f64)         |
| v128.reinterpret/i64x2 |       (i64 i64): (v128)        |
| v128.reinterpret/i32x4 |  (i32 i32 i32 i32): (v128) |
| v128.reinterpret/f64x2 |       (f64 f64): (v128)       |
| v128.reinterpret/f32x4 | (f32 f32 f32 f32): (v128) |
| i64x2.reinterpret/v128 |       (v128): (i64 i64)        |
| i32x4.reinterpret/v128 | (v128): (i32 i32 i32 i32)  |
| f64x2.reinterpret/v128 |       (v128): (f64 f64)       |
| f32x4.reinterpret/v128 | (v128): (f32 f32 f32 f32) |

Consider this function:
```wat
(func (export "add") (param i64)
	local.get 0
	i32x2.reinterpret/i64
	i32.add
)
```

The body of that function would directly map to the following x64 Asm:
```
add eax, eax
```

But all the instructions would need to do is pop different amounts of bits from the VM's stack.
Technically, they could all be `nop`s, that just change how an implementation validates instructions.

**Comment by lars-t-hansen** [comment]
What might be concrete use cases for some of these instructions?

As far as some of them are concerned they are in the SIMD spec; f64x2.reinterpret/v128 is just f64x2.extract_lane twice, for example, and having a dedicated reinterpret instruction will likely not improve the code.

**Comment by 00ff0000red** [comment]
Two `f64x2.extract_lane` operations would require an extra variable to store the SIMD vector.
```wat
(func (export "add") (param v128) (result f64)
	(local $temp v128)
	local.get 0
	local.tee $temp
	f64x2.extract_lane 0
	local.get $temp
	f64x2.extract_lane 1
	f64.add
)
```

All reinterpretation instructions (including the existing f32<->i32 and f64<->i64) could be emulated by loading and storing from memory, why not directly use the stack as memory?

How common is it for someone to perform SIMD operations on a vector, then want to convert it back to its scalar values and use them individually?

**Comment by lars-t-hansen** [comment]
I don't understand why the temp is needed, why wouldn't you use the following?
```
local.get 0
f64x2.extract_lane 0
local.get 0
f64x2.extract_lane 1
f64.add
```
In current Firefox this turns into:
```
00000020  55                        push %rbp
00000021  48 8b ec                  mov %rsp, %rbp
00000024  66 0f 6f d0               movdqa %xmm0, %xmm2
00000028  66 0f 6f ca               movdqa %xmm2, %xmm1
0000002C  66 0f 3a 0f c1 08         palignr $0x08, %xmm1, %xmm0
00000032  66 0f 28 c9               movapd %xmm1, %xmm1
00000036  f2 0f 58 c1               addsd %xmm1, %xmm0
0000003A  5d                        pop %rbp
0000003B  c3                        ret
```
where the `mov` nest before the `palignr` is a register allocation problem that ought to be fixed (there's no sense in going via xmm2) and the movapd at ...32 is redundant (and I'll make sure this is fixed).  This leaves you with `movdqa; palignr; addsd` which is possibly not quite optimal - `palignr; addsd` would be enough, with the right register assignments - but not bad.

Still, I'm asking for concrete use cases, while I think what you're offering in your last paragraph is more rhetorical.  Clearly, "horizontal sum" is a thing for SIMD but it has not been a prominent enough problem to warrant an instruction in the emerging wasm SIMD spec.  It may be fruitful to move this discussion to the SIMD repo.

**Comment by 00ff0000red** [comment]
Okay, that was a very poor example, I'd think we would need more Wat to see where this would be helpful.

> Still, I'm asking for concrete use cases, while I think what you're offering in your last paragraph is more rhetorical.

Indeed, it really was, but that might be the major use case for these, at least regarding the v128 reinterpretation operations.
Otherwise, the only other use that comes to mind is loading multiple values from memory at once.

```wat
(func $load_i32x4 (param i32) (result i32 i32 i32 i32)
    local.get 0
    i32.load

    local.get 0
    i32.load offset=4

    local.get 0
    i32.load offset=8

    local.get 0
    i32.load offset=12
)
```
vs
```wat
(func $load_i32x4 (param i32) (result i32 i32 i32 i32)
    local.get 0
    v128.load
    i32x4.reinterpret/v128
)
```

Loading as much as possible at once is helpful for algorithms such as, say, an `indexOf` implementation, since the only way to really improve performance would be to vectorize operations or use more threads.

> It may be fruitful to move this discussion to the SIMD repo.

By all means, if it would be better suited to move this into any specific proposal, I'm fine with it being moved to where it would best fit.

**Comment by lars-t-hansen** [comment]
OK, that's an interesting piece of code.  In idiomatic wasm that might be:
```
  (func (export "f") (param i32) (result i32 i32 i32 i32)
    (local v128)
    (i32x4.extract_lane 0 (local.tee 1 (v128.load (local.get 0))))
    (i32x4.extract_lane 1 (local.get 1))
    (i32x4.extract_lane 2 (local.get 1))
    (i32x4.extract_lane 3 (local.get 1)))
```
and because Firefox passes multiple results through memory (except the last, which is passed through a register), we get
```
00000020  55                        push %rbp
00000021  48 8b ec                  mov %rsp, %rbp
00000024  41 0f 10 04 3f            movupsx (%r15,%rdi,1), %xmm0
00000029  66 0f 7e c1               movd %xmm0, %ecx
0000002D  66 0f 3a 16 c2 01         pextrd $0x01, %xmm0, %edx
00000033  66 0f 3a 16 c0 02         pextrd $0x02, %xmm0, %eax
00000039  66 0f 3a 16 c3 03         pextrd $0x03, %xmm0, %ebx
0000003F  89 4e 10                  movl %ecx, 0x10(%rsi)
00000042  89 56 08                  movl %edx, 0x08(%rsi)
00000045  89 06                     movl %eax, (%rsi)
00000047  8b c3                     mov %ebx, %eax
00000049  5d                        pop %rbp
0000004A  c3                        ret
```
which is not squeaky clean (loading lane 3 into eax and lane 2 into ebx would have saved a move), but, apart from saving bytecode space at the wasm level, it doesn't feel like we could do much better with a dedicated instruction for this operation.

**Comment by 00ff0000red** [comment]
Thank you for giving your opinion on this.
If no one else thinks that it may be worth the cost to add to Wasm, then I'll likely close this issue soon.

**Comment by rossberg** [comment]
One thing to be careful about with transformations like these is that they are not generally equivalence-preserving in the presence of threads: i32 loads are guaranteed not to tear, whereas a v128 load can tear per byte. So a compiler may have to be able to prove that there are no races in order to apply these as optimisations.

**Comment by 00ff0000red** [comment]
@rossberg That is good point, but with the example that I had given, a memory searching function (`index_of`), with threads you can still get the same performance, as the code is split across CPU cores.

But, even then, it doesn't have to be a v128 load, it could be `i64.load` followed by a `i32x2.reinterpret/i64`, which would have less memory bounds checks, and more loaded per operation, therefore it *should* still result in improved performance.
